runtime: python39
entrypoint: gunicorn -b :$PORT main:app

instance_class: F4

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /.*
  script: auto

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "token.json"